name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 MSBuild 路径
        uses: microsoft/setup-msbuild@v2

      - name: 恢复 NuGet 包
        uses: NuGet/setup-nuget@v2
      - run: nuget restore

      - name: 编译项目
        run: msbuild /p:Configuration=Release /p:SignManifests=false

      - name: 打包所有 Release 产物
        run: |
          $zip = "${{ github.event.repository.name }}-${{ github.ref_name || github.run_number }}.zip"
          $releaseDirs = Get-ChildItem -Path . -Recurse -Directory -Filter Release
          foreach ($dir in $releaseDirs) {
            Compress-Archive -Path "$($dir.FullName)\*" -DestinationPath $zip -Update
          }
        shell: pwsh

      - name: 上传 artifact（无 tag 时）
        if: startsWith(github.ref, 'refs/tags/') == false
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ${{ github.event.repository.name }}-${{ github.ref_name || github.run_number }}.zip

      - name: 创建 Release 并上传资源（有 tag 时）
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.event.repository.name }}-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
